# Workflow for testing installing, running, and uninstalling OpenBakery
name: Install & Run

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.txt'

  pull_request:
    types:
      - opened
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.txt'

jobs:
  install-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # unshallow fetch for setuptools-scm (otherwise the version is always 0.1.dev1)

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install OpenBakery (no extras)
      run: |
        python -m pip install .
        openbakery -h
        openbakery --version

    - name: Run Universal checks
      run: >-
        openbakery check-universal
        -x win_ascent_and_descent
        -x os2_metrics_match_hhea
        -x soft_dotted
        data/test/source-sans-pro/OTF/SourceSansPro-Regular.otf
        data/test/source-sans-pro/OTF/SourceSansPro-Italic.otf;
        openbakery check-universal
        -x win_ascent_and_descent
        -x os2_metrics_match_hhea
        -x fsselection
        -x valid_default_instance_nameids
        -x soft_dotted
        data/test/source-sans-pro/VAR/SourceSansVariable-Roman.ttf

    - name: Try running UFO Sources checks
      run: >-
        openbakery check-ufo-sources --verbose data/test/test.ufo
        || exit 0
      shell: bash

    - name: Install `ufo-sources` extra
      run: |
        python -m pip install '.[ufo-sources]'

    - name: Run UFO Sources checks
      run: >-
        openbakery check-ufo-sources --verbose data/test/test.ufo;
        openbakery check-ufo-sources -x designspace_has_consistent
        "data/test/stupidfont/Stupid Font.designspace"

    - name: Install `googlefonts` extra
      run: |
        python -m pip install '.[googlefonts]'

    - name: Run Google Fonts checks
      run: >-
        openbakery check-googlefonts
        -c canonical_filename
        -c vendor_id
        -c glyph_coverage
        -c name/license
        -c hinting_impact
        -c unreachable_glyphs
        -c contour_count
        -c outline_colinear_vectors
        data/test/cabin/Cabin-*.ttf

    - name: Uninstall OpenBakery
      run: |
        python -m pip uninstall openbakery -y
